name: replace tokens
author: CodeByJacob
description: Github Action to replace token
inputs:
  files:
    description: 'Files to replace'
    required: true
    default: ""
  prefix:
    description: 'Token prefix'
    required: false
    default: "#{"
  suffix:
    description: 'Token suffix'
    required: false
    default: "}#"

runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Set up configuration
      run: |
        echo "INPUT_WORK_PATH=${{ github.workspace }}/" >> $GITHUB_ENV
        echo "INPUT_FILES=${{ inputs.files }}" >> $GITHUB_ENV
        echo "INPUT_SUFFIX=${{ inputs.suffix }}" >> $GITHUB_ENV
        echo "INPUT_PREFIX=${{ inputs.prefix }}" >> $GITHUB_ENV
      shell: bash

    - name: Replace tokens
      working-directory: ${{ github.action_path }}
      run: python3 main.py
      shell: bash
